version: 2
registries:
  artifactory:
    type: rubygems-server
    url: ${{secrets.ARTIFACTORY_URL}}
    username: ${{secrets.ARTIFACTORY_USERNAME}}
    password: ${{secrets.ARTIFACTORY_API_KEY}}
updates:
  - package-ecosystem: "bundler"
    vendor: true
    directory: "/"
    registries:
      - artifactory
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct" # only explicitly defined dependencies.
